service: member-profile-admin-lambda

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.0
  role: ${file(./config/${self:provider.stage}.json):LAMBDA_ROLE}
  environment:
    M2M_AUTH_AUDIENCE: ${file(./config/${self:provider.stage}.json):M2M_AUTH_AUDIENCE}
    M2M_AUTH_CLIENT_ID: ${file(./config/${self:provider.stage}.json):M2M_AUTH_CLIENT_ID}
    M2M_AUTH_CLIENT_SECRET: ${file(./config/${self:provider.stage}.json):M2M_AUTH_CLIENT_SECRET}
    M2M_AUTH_DOMAIN: ${file(./config/${self:provider.stage}.json):M2M_AUTH_DOMAIN}
    KAFKA_URL: ${file(./config/${self:provider.stage}.json):KAFKA_URL}
    UPDATE_PROFILE_TOPIC: ${file(./config/${self:provider.stage}.json):UPDATE_PROFILE_TOPIC}
    UPDATE_PROFILE_TRAIT_TOPIC: ${file(./config/${self:provider.stage}.json):UPDATE_PROFILE_TRAIT_TOPIC}
    ORIGINATOR: ${file(./config/${self:provider.stage}.json):ORIGINATOR}

functions:
  profile:
    handler: member.profile
    events:
     - http:
         path: member/profile
         method: get
  profiletraits:
    handler: member.profiletraits
    events:
     - http:
         path: member/profiletraits
         method: get
